services:
  db:
    image: postgres:15
    container_name: zhigalev_travel_db
    restart: always
    environment:
      POSTGRES_DB: zhigalev_travel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: zhigalev_travel_web
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/zhigalev_travel

volumes:
  postgres_data:
