# Generated by Django 5.2.7 on 2025-10-12 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, unique=True, verbose_name="Номер комнаты"),
                ),
                (
                    "price_per_night",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена за ночь"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступна для бронирования"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Номер",
                "verbose_name_plural": "Номера",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("check_in", models.DateField(verbose_name="Дата заезда")),
                ("check_out", models.DateField(verbose_name="Дата выезда")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="rooms.room",
                        verbose_name="Номер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "ordering": ["-created_at"],
            },
        ),
    ]
