# Generated by Django 5.2.7 on 2025-10-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["room"], name="rooms_booki_room_id_c2f7ab_idx"),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["number"], name="rooms_room_number_3f2cd6_idx"),
        ),
    ]
